version: '3.0'

volumes:
  jenkins-home:
    driver: local

services:
  jenkins:
    image: waltervargas/gnome-jenkins:latest
    ports:
      - 8080:8080
    volumes:
      - jenkins-home:/var/jenkins_home

  bugzilla:
    container_name: bugzilla-dev
    image: bugzilla/bugzilla-dev
    ports:
      - "80:80"
      - "5900:5900"
